#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C

if [[ -z $1 ]]; then
	echo -e "\e[00;1;92mError: Debe indicar la longitud de la clave a generar\e[00m"
	exit 1
else
	< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c "$1";echo;
fi

exit 0
