#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C

if [[ -z $1 ]]; then
	< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c 8;echo;
else
	< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c "$1";echo;
fi

exit 0
